//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanGazV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_607_gaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_607_gaz()
        {
            this.tbl_607_join_bottle_gaz = new HashSet<tbl_607_join_bottle_gaz>();
        }
    
        public int ID { get; set; }
        public int FK_ID_theorical_content { get; set; }
        public int FK_ID_made_tolerance { get; set; }
        public int FK_ID_gaz_type { get; set; }
        public int FK_ID_testing_tolerance { get; set; }
        public int FK_ID_order_details { get; set; }
        public int FK_ID_unit_made_tolerance { get; set; }
        public int FK_ID_unit_testing_tolerance { get; set; }
        public int FK_ID_unit_theorical_content { get; set; }
    
        public virtual tbl_607_gaz_type tbl_607_gaz_type { get; set; }
        public virtual tbl_607_made_tolerance tbl_607_made_tolerance { get; set; }
        public virtual tbl_607_units tbl_607_units { get; set; }
        public virtual tbl_607_order_details tbl_607_order_details { get; set; }
        public virtual tbl_607_testing_tolerance tbl_607_testing_tolerance { get; set; }
        public virtual tbl_607_units tbl_607_units1 { get; set; }
        public virtual tbl_607_theorical_content tbl_607_theorical_content { get; set; }
        public virtual tbl_607_units tbl_607_units2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_607_join_bottle_gaz> tbl_607_join_bottle_gaz { get; set; }
    }
}
