//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanGazV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_607_provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_607_provider()
        {
            this.tbl_607_order = new HashSet<tbl_607_order>();
        }

        public int ID { get; set; }

        [Required(ErrorMessage = "is required")]
        [RegularExpression(@"[A-Za-z0-9]+", ErrorMessage = "Only alpha-numeric (no symbols)")]
        public string provider_name { get; set; }

        [Required(ErrorMessage = "is required")]
        [RegularExpression(@"[0-9a-zA-Z #,-]+", ErrorMessage = "Only alphanumeric, spaces, #, ',', - (no symbols & accented)")]
        public string adress { get; set; }

        [Required(ErrorMessage = "is required")]
        [RegularExpression(@"[0-9]+", ErrorMessage = "Only numeric")]
        public string cp { get; set; }

        [Required(ErrorMessage = "is required")]
        public string town { get; set; }

        [RegularExpression(@"^\s*\+?\s*([0-9][\s-]*){9,}$", ErrorMessage = "Only numeric, spaces, -, +")]
        public string phone { get; set; }

        [RegularExpression(@"^\s*\+?\s*([0-9][\s-]*){9,}$", ErrorMessage = "Only numeric, spaces, -, +")]
        public string fax { get; set; }

        [Required(ErrorMessage = "Email id is required")]
        [RegularExpression(@"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", ErrorMessage = "Please enter a valid email address")]
        public string mail { get; set; }

        [RegularExpression(@"[0-9a-zA-Z #,-]+", ErrorMessage = "Only alphanumeric, spaces, #, ',', - (no symbols)")]
        public string adress_compl { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_607_order> tbl_607_order { get; set; }
    }
}
