//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanGazV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_607_join_bottle_gaz
    {
        public int FK_ID_gaz { get; set; }
        public int FK_ID_bottle { get; set; }
        public int ID { get; set; }
        public Nullable<int> FK_ID_real_content { get; set; }
    
        public virtual tbl_607_bottle tbl_607_bottle { get; set; }
        public virtual tbl_607_gaz tbl_607_gaz { get; set; }
        public virtual tbl_607_real_gaz_content tbl_607_real_gaz_content { get; set; }
    }
}
