//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanGazV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_607_gaz_reporting
    {
        public int ID { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime reporting_date { get; set; }
        public int FK_ID_actors { get; set; }
        public int pressure_value { get; set; }
        public int FK_ID_bottle { get; set; }
    
        public virtual tbl_607_actors tbl_607_actors { get; set; }
        public virtual tbl_607_bottle tbl_607_bottle { get; set; }
    }
}
