//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanGazV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_607_order_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_607_order_details()
        {
            this.tbl_607_gaz = new HashSet<tbl_607_gaz>();
            this.tbl_607_shipping_request_details = new HashSet<tbl_607_shipping_request_details>();
        }
    
        public int ID { get; set; }
        public int order_quantity { get; set; }
        public int recieved_quantity { get; set; }
        public int poste_number { get; set; }
        public int shipping_delays { get; set; }
        public int gaz_lifetime { get; set; }
        public int FK_ID_packaging { get; set; }
        public int FK_ID_order { get; set; }
        public int stock_mini { get; set; }
        public string content_comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_607_gaz> tbl_607_gaz { get; set; }
        public virtual tbl_607_order tbl_607_order { get; set; }
        public virtual tbl_607_packaging tbl_607_packaging { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_607_shipping_request_details> tbl_607_shipping_request_details { get; set; }
    }
}
