//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanGazV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_607_provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_607_provider()
        {
            this.tbl_607_order = new HashSet<tbl_607_order>();
        }
    
        public int ID { get; set; }
        public string provider_name { get; set; }
        public string adress { get; set; }
        public string cp { get; set; }
        public string town { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string mail { get; set; }
        public string adress_compl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_607_order> tbl_607_order { get; set; }
    }
}
