//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanGazV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_607_bottle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_607_bottle()
        {
            this.tbl_607_gaz_reporting = new HashSet<tbl_607_gaz_reporting>();
            this.tbl_607_join_bottle_gaz = new HashSet<tbl_607_join_bottle_gaz>();
        }
    
        public int ID { get; set; }
        public string manufacturer_bottle_number { get; set; }
        public string bottle_conti_number { get; set; }
        public int FK_ID_location { get; set; }
        public int FK_ID_shipping_delivery { get; set; }
        public int FK_ID_order { get; set; }
        public int FK_ID_conformity_certificate { get; set; }
    
        public virtual tbl_607_conformity_certificate tbl_607_conformity_certificate { get; set; }
        public virtual tbl_607_location tbl_607_location { get; set; }
        public virtual tbl_607_order tbl_607_order { get; set; }
        public virtual tbl_607_shipping_delivery tbl_607_shipping_delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_607_gaz_reporting> tbl_607_gaz_reporting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_607_join_bottle_gaz> tbl_607_join_bottle_gaz { get; set; }
    }
}
