//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanGazV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_607_shipping_request_details
    {
        public int ID { get; set; }
        public Nullable<int> shipping_quantity { get; set; }
        public int FK_shipping_request { get; set; }
        public int FK_ID_order_details { get; set; }
        public Nullable<int> reception_quantity { get; set; }
    
        public virtual tbl_607_order_details tbl_607_order_details { get; set; }
        public virtual tbl_607_shipping_request tbl_607_shipping_request { get; set; }
    }
}
